Allow the user to set a custom status code in the safehttp.ResponseWriter
google/go-safeweb pull request #209
Opened 2020-10-19 10:55 UTC by maramihali

Fixes #151

Previously, there was no way of setting a status code other than `safehttp.NoContent` as the write method in the `safehttp.ResponseWriter` would always set the status code to `safehttp.StatusOK`. Implemented initial functionality and tests to make this possible.

2020-10-19 11:03 UTC, kele reviewed
What should happen if someone calls `SetCode` and then `NoContent`, `Redirect` or `WriteError`?

2020-10-19 12:16 UTC, maramihali commented
Currently, whatever `ResponseWriter.code` was set to by calling `SetCode` would be ignored and the response status will be set properly. That situation would be a bug, but should we actually error/panic in that case? It might be a bit extreme to panic, I don't know whether returning a 500 would be better than ignoring. :-?

2020-10-19 12:21 UTC, kele commented
It's not clear that it would always be a bug.

Imagine you call `SetCode()` at the beginning (because you know your handler returns this code), but you encounter an error and want to gracefully recover with `WriteError()`. I don't see a more ergonomic way to do this than what I described, so that shouldn't be treated as a bug.

2020-10-19 12:28 UTC, maramihali commented
Right now it is not treated as a bug and the behavior is the one described by you (btw I should write tests to exemplify this, thanks for pointing it out).

2020-10-19 12:50 UTC, kele approved these changes

2020-10-20 09:46 UTC, empijei requested changes

2020-10-20 09:46 UTC, empijei commented on safehttp/response_writer.go
> +	}
I would not panic here. I would actually do nothing in this case. This is not an error worth panicking for, and if we have already indeed written something it's not like we can change the status to a 500, so I would just do nothing in this case and document that if we have already written calling SetCode does nothing.

This would likely either be a non-issue or a small bug, definitely hard to find this as an exploitable vulnerability, so I would not invest too much in making this hard to get wrong.

2020-10-20 12:01 UTC, empijei approved these changes

2020-10-20 12:01 UTC, merged